from workflow_loader import load_workflow
from executor import execute_workflow
import shutil
from pathlib import Path


def main():
    workflow_path = "/workspace/workflows/patient_import_v3.json"

    workflow = load_workflow(workflow_path)

    workflow_id = workflow.get("workflow_id")
    run_id = workflow.get("run_id")
    max_iterations = workflow.get("max_iterations", 1)
    steps = workflow.get("steps", [])

    # Start each workflow run with a clean run directory.
    # This prevents old prompt versions, logs, and results
    # from previous executions from affecting the current run.
    run_dir = Path(f"/workspace/runs/{run_id}")
    if run_dir.exists():
        shutil.rmtree(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Create the shared workflow context ONCE.
    # This object will be reused across all iterations.
    # That means values written during iteration 1
    # will still exist in iteration 2 and 3.
    context = {
        "steps": {},
        "run_id": run_id,
        "shared": {
            # This starts as None and can later be replaced
            # by an improved prompt file generated by AI.
            "current_prompt_file": None
        }
    }

    print(f"Loaded workflow: {workflow_id}")
    print(f"Run id: {run_id}")
    print(f"Max iterations: {max_iterations}")
    print(f"Steps: {len(steps)}")

    for iteration in range(1, max_iterations + 1):
        print(f"\n=== Iteration {iteration}/{max_iterations} ===")

        # Clear per-step results for this iteration.
        # We keep shared values such as current_prompt_file.
        context["steps"] = {}

        workflow_result = execute_workflow(workflow, context)
        print(f"Workflow result: {workflow_result}")

        if workflow_result.get("status") == "success":
            print("Workflow completed successfully.")
            return

        if workflow_result.get("status") == "retry":
            print("Workflow requested retry.")
            print(
                "Current prompt for next iteration: "
                f"{context['shared'].get('current_prompt_file')}"
            )
            continue

        raise RuntimeError(f"Unexpected workflow status: {workflow_result}")

    print("Workflow stopped: max iterations reached.")


if __name__ == "__main__":
    main()